#!/usr/bin/env python3
"""Generate the native PromQL support matrix in the ClickHouse documentation.

Refresh the compliance snapshot and matrix from the repository root:

    python3 -m ci.praktika run "integration" \
      --test "test_prometheus_protocols/test_compliance.py::test_promql_compliance" \
      --path build/programs/clickhouse \
      --param COMPLIANCE_RESULT_FILE=ci/jobs/scripts/docs/promql_compliance_results.json
    python3 ci/jobs/scripts/docs/generate_promql_support_matrix.py --write
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_CATALOG = Path(__file__).with_name("promql_support_catalog.json")
DEFAULT_COMPLIANCE = Path(__file__).with_name("promql_compliance_results.json")
DEFAULT_PAGE = REPO_ROOT / "docs/guides/use-cases/observability/promql-support-matrix.mdx"
PROMQL_SOURCE = REPO_ROOT / "src/Storages/TimeSeries/PrometheusQueryToSQL"
START_MARKER = "{/*AUTOGENERATED_START*/}"
END_MARKER = "{/*AUTOGENERATED_END*/}"

MAP_ENTRY_RE = re.compile(r'^\s*\{"([a-z][a-z0-9_]*)",', re.MULTILINE)
NAME_COMPARISON_RE = re.compile(
    r'(?:function_name|operator_name)\s*(?:==|!=)\s*"([a-z][a-z0-9_]*)"'
)
QUERY_CALL_RE = re.compile(r"(?<![A-Za-z0-9_:])([A-Za-z_][A-Za-z0-9_]*)\s*\(")
NOT_IMPLEMENTED_RES = (
    re.compile(r"Function '?([A-Za-z_][A-Za-z0-9_]*)'? is not implemented", re.IGNORECASE),
    re.compile(
        r"Aggregation operator '([A-Za-z_][A-Za-z0-9_]*)' is not implemented",
        re.IGNORECASE,
    ),
)


def load_catalog(path: Path) -> dict:
    catalog = json.loads(path.read_text(encoding="utf-8"))
    names = [
        feature["name"]
        for category in catalog["categories"]
        for feature in category["features"]
    ]
    if len(names) != len(set(names)):
        duplicates = sorted(name for name, count in Counter(names).items() if count > 1)
        raise ValueError(f"Duplicate catalog features: {', '.join(duplicates)}")
    return catalog


def load_compliance(path: Path) -> dict:
    compliance = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "passed",
        "failed",
        "unsupported",
        "total",
        "metadata",
        "results",
    }
    missing = required - compliance.keys()
    if missing:
        raise ValueError(
            f"Compliance JSON is missing required fields: {', '.join(sorted(missing))}"
        )

    metadata_required = {"clickhouse_version", "clickhouse_revision"}
    metadata_missing = metadata_required - compliance["metadata"].keys()
    if metadata_missing:
        raise ValueError(
            "Compliance metadata is missing required fields: "
            + ", ".join(sorted(metadata_missing))
        )

    valid_outcomes = {"passed", "failed", "unsupported"}
    for index, result in enumerate(compliance["results"]):
        missing_result_fields = {"query", "outcome"} - result.keys()
        if missing_result_fields:
            raise ValueError(
                f"Compliance result {index} is missing required fields: "
                + ", ".join(sorted(missing_result_fields))
            )
        if result["outcome"] not in valid_outcomes:
            raise ValueError(
                f"Compliance result {index} has unknown outcome: {result['outcome']}"
            )

    outcome_counts = Counter(result["outcome"] for result in compliance["results"])
    for outcome in ("passed", "failed", "unsupported"):
        if outcome_counts[outcome] != compliance[outcome]:
            raise ValueError(
                f"Compliance {outcome} count does not match detailed results"
            )
    if len(compliance["results"]) != compliance["total"]:
        raise ValueError("Compliance total does not match detailed results")
    return compliance


def extract_implemented_features(source_dir: Path, catalog_names: set[str]) -> set[str]:
    candidates: set[str] = set()
    for pattern in ("*.cpp", "*.h"):
        for source_path in sorted(source_dir.glob(pattern)):
            source = source_path.read_text(encoding="utf-8")
            candidates.update(MAP_ENTRY_RE.findall(source))
            candidates.update(NAME_COMPARISON_RE.findall(source))
    return candidates & catalog_names


def extract_query_features(
    query: str,
    catalog_names: set[str],
    aggregation_names: set[str],
) -> set[str]:
    features = set(QUERY_CALL_RE.findall(query)) & catalog_names
    for name in aggregation_names:
        pattern = re.compile(
            rf"(?<![A-Za-z0-9_:]){re.escape(name)}\s+"
            rf"(?:by|without)\s*\([^)]*\)\s*\(",
            re.IGNORECASE,
        )
        if pattern.search(query):
            features.add(name)
    return features


def extract_not_implemented_feature(reason: str) -> str | None:
    for pattern in NOT_IMPLEMENTED_RES:
        if match := pattern.search(reason):
            return match.group(1)
    return None


def aggregate_compliance(
    results: list[dict],
    catalog_names: set[str],
    aggregation_names: set[str],
) -> dict[str, Counter]:
    counts = {name: Counter() for name in catalog_names}
    for result in results:
        query = result["query"]
        outcome = result["outcome"]
        reason = result.get("reason", "")
        features = extract_query_features(query, catalog_names, aggregation_names)
        unsupported_feature = (
            extract_not_implemented_feature(reason) if outcome == "unsupported" else None
        )
        if unsupported_feature in catalog_names:
            features.add(unsupported_feature)

        for feature in features:
            if outcome == "passed":
                counts[feature]["passed"] += 1
            elif outcome == "unsupported" and feature == unsupported_feature:
                counts[feature]["unsupported"] += 1
            else:
                counts[feature]["differences"] += 1
    return counts


def format_compliance(counts: Counter) -> str:
    total = counts["passed"] + counts["differences"] + counts["unsupported"]
    if not total:
        return "Not covered"
    return (
        f"Passed: {counts['passed']}; differences: {counts['differences']}; "
        f"unsupported: {counts['unsupported']}"
    )


def render_matrix(catalog: dict, implemented: set[str], compliance: dict) -> str:
    metadata = compliance["metadata"]
    results = compliance["results"]
    catalog_names = {
        feature["name"]
        for category in catalog["categories"]
        for feature in category["features"]
    }
    aggregation_names = {
        feature["name"]
        for category in catalog["categories"]
        for feature in category["features"]
        if feature.get("kind") == "aggregation"
    }
    counts = aggregate_compliance(results, catalog_names, aggregation_names)
    covered_features = {
        name
        for name, feature_counts in counts.items()
        if sum(feature_counts.values()) > 0
    }

    lines = [
        (
            f"Compliance snapshot: ClickHouse `{metadata['clickhouse_version']}` "
            f"(`{metadata['clickhouse_revision']}`), {compliance['total']} test cases."
        ),
        "",
    ]

    for category in catalog["categories"]:
        covered_category_features = [
            feature
            for feature in category["features"]
            if feature["name"] in covered_features
        ]
        if not covered_category_features:
            continue
        lines.extend(
            [
                f"## {category['name']} {{#{category['slug']}}}",
                "",
                "| PromQL feature | Native status | Compliance query outcomes | Notes |",
                "|---|---|---|---|",
            ]
        )
        for feature in covered_category_features:
            name = feature["name"]
            if name not in implemented:
                status = "Not supported"
            elif feature.get("partial"):
                status = "Partial"
            else:
                status = "Supported"
            note = feature.get("note", "")
            lines.append(
                f"| `{name}` | {status} | {format_compliance(counts[name])} | {note} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def replace_generated_region(page: str, generated: str) -> str:
    if page.count(START_MARKER) != 1 or page.count(END_MARKER) != 1:
        raise ValueError("The documentation page must contain one generated marker pair")
    start, remainder = page.split(START_MARKER, 1)
    _, end = remainder.split(END_MARKER, 1)
    return f"{start}{START_MARKER}\n{generated}{END_MARKER}{end}"


def generate(
    catalog_path: Path,
    page_path: Path,
    source_dir: Path,
    compliance_path: Path,
) -> str:
    catalog = load_catalog(catalog_path)
    catalog_names = {
        feature["name"]
        for category in catalog["categories"]
        for feature in category["features"]
    }
    implemented = extract_implemented_features(source_dir, catalog_names)
    compliance = load_compliance(compliance_path)
    generated = render_matrix(catalog, implemented, compliance)
    return replace_generated_region(page_path.read_text(encoding="utf-8"), generated)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--page", type=Path, default=DEFAULT_PAGE)
    parser.add_argument("--source-dir", type=Path, default=PROMQL_SOURCE)
    parser.add_argument("--compliance-json", type=Path, default=DEFAULT_COMPLIANCE)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = generate(
        args.catalog,
        args.page,
        args.source_dir,
        args.compliance_json,
    )
    current = args.page.read_text(encoding="utf-8")
    if args.check:
        if current != expected:
            print(f"{args.page} is not up to date", file=sys.stderr)
            return 1
        return 0

    args.page.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
