#!/usr/bin/env python3

import json
import tempfile
import unittest
from pathlib import Path

import generate_promql_support_matrix as matrix


class PromQLSupportMatrixTest(unittest.TestCase):
    def test_native_feature_extraction(self):
        catalog = matrix.load_catalog(matrix.DEFAULT_CATALOG)
        names = {
            feature["name"]
            for category in catalog["categories"]
            for feature in category["features"]
        }
        implemented = matrix.extract_implemented_features(matrix.PROMQL_SOURCE, names)

        self.assertTrue(
            {
                "rate",
                "last_over_time",
                "abs",
                "sin",
                "day_of_month",
                "label_replace",
                "histogram_quantile",
                "scalar",
                "vector",
                "time",
                "pi",
                "sum",
                "quantile",
                "topk",
            }
            <= implemented
        )
        self.assertTrue(
            {
                "avg_over_time",
                "absent",
                "clamp",
                "count_values",
                "histogram_avg",
                "round",
            }.isdisjoint(implemented)
        )

    def test_exact_unsupported_attribution(self):
        names = {"rate", "avg_over_time"}
        results = [
            {
                "query": "avg_over_time(rate(metric[1m])[2m:10s])",
                "outcome": "unsupported",
                "reason": "Function avg_over_time is not implemented",
            }
        ]

        counts = matrix.aggregate_compliance(results, names, set())

        self.assertEqual(counts["avg_over_time"]["unsupported"], 1)
        self.assertEqual(counts["rate"]["differences"], 1)
        self.assertEqual(counts["rate"]["unsupported"], 0)

    def test_pass_and_difference_attribution(self):
        names = {"abs", "rate"}
        results = [
            {"query": "abs(metric)", "outcome": "passed", "reason": ""},
            {
                "query": "abs(rate(metric[5m]))",
                "outcome": "failed",
                "reason": "series count mismatch",
            },
        ]

        counts = matrix.aggregate_compliance(results, names, set())

        self.assertEqual(counts["abs"], {"passed": 1, "differences": 1})
        self.assertEqual(counts["rate"], {"differences": 1})

    def test_aggregation_modifier_attribution(self):
        names = {"sum", "max"}
        results = [
            {
                "query": "sum by(job) (max without(instance) (metric))",
                "outcome": "passed",
                "reason": "",
            }
        ]

        counts = matrix.aggregate_compliance(results, names, names)

        self.assertEqual(counts["sum"], {"passed": 1})
        self.assertEqual(counts["max"], {"passed": 1})

    def test_generated_region_replacement(self):
        page = "before\n{/*AUTOGENERATED_START*/}\nold\n{/*AUTOGENERATED_END*/}\nafter\n"
        expected = (
            "before\n{/*AUTOGENERATED_START*/}\nnew\n"
            "{/*AUTOGENERATED_END*/}\nafter\n"
        )

        self.assertEqual(matrix.replace_generated_region(page, "new\n"), expected)

    def test_compliance_result_validation(self):
        compliance = {
            "passed": 1,
            "failed": 0,
            "unsupported": 0,
            "total": 1,
            "metadata": {
                "clickhouse_version": "26.8.1.1",
                "clickhouse_revision": "abc123",
            },
            "results": [{"outcome": "passed"}],
        }

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "results.json"
            path.write_text(json.dumps(compliance), encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "missing required fields: query"):
                matrix.load_compliance(path)

    def test_generate_from_fixture(self):
        catalog = {
            "categories": [
                {
                    "name": "Functions",
                    "slug": "functions",
                    "features": [
                        {"name": "rate"},
                        {"name": "absent"},
                        {"name": "uncovered"},
                    ],
                },
                {
                    "name": "Uncovered functions",
                    "slug": "uncovered-functions",
                    "features": [{"name": "also_uncovered"}],
                }
            ]
        }
        compliance = {
            "passed": 1,
            "failed": 0,
            "unsupported": 1,
            "total": 2,
            "pct": 50.0,
            "metadata": {
                "clickhouse_version": "26.8.1.1",
                "clickhouse_revision": "abc123",
            },
            "results": [
                {"query": "rate(metric[5m])", "outcome": "passed", "reason": ""},
                {
                    "query": "absent(metric)",
                    "outcome": "unsupported",
                    "reason": "Function absent is not implemented",
                },
            ],
        }

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            catalog_path = root / "catalog.json"
            page_path = root / "page.mdx"
            source_dir = root / "src"
            compliance_path = root / "results.json"
            source_dir.mkdir()
            catalog_path.write_text(json.dumps(catalog), encoding="utf-8")
            compliance_path.write_text(json.dumps(compliance), encoding="utf-8")
            page_path.write_text(
                "{/*AUTOGENERATED_START*/}\n{/*AUTOGENERATED_END*/}\n",
                encoding="utf-8",
            )
            (source_dir / "apply.cpp").write_text(
                'static const auto impl_map = {\n    {"rate", {"timeSeriesRateToGrid"}},\n};',
                encoding="utf-8",
            )

            generated = matrix.generate(
                catalog_path, page_path, source_dir, compliance_path
            )

        self.assertIn("| `rate` | Supported | Passed: 1; differences: 0; unsupported: 0", generated)
        self.assertIn("| `absent` | Not supported | Passed: 0; differences: 0; unsupported: 1", generated)
        self.assertNotIn("`uncovered`", generated)
        self.assertNotIn("Uncovered functions", generated)


if __name__ == "__main__":
    unittest.main()
